AWSTemplateFormatVersion: 2010-09-09 
Metadata:
  'AWS::CloudFormation::Designer': {}
Resources:
  sachin7AMto7PM:
    Type: 'Custom::ServiceInstanceSchedule'
    Properties:
      Name: Sachin-OfficeHours
      NoStackPrefix: 'True'
      Description: Office hours in Ind
      ServiceToken: >-
        arn:aws:lambda:us-east-1:205421220812:function:rds-schedular-InstanceSchedulerMain
      Enforced: 'True'
      UseMaintenanceWindow: 'True'
      Timezone: Asia/Kolkata
      Periods:
        - Description: Opening hours on weekdays
          BeginTime: '08:00'
          EndTime: '18:00'
          WeekDays: Mon-Fri
        - Description: Opening hours in weekend
          BeginTime: '09:00'
          EndTime: '17:00'
          WeekDays: Sat-Sun