AWSTemplateFormatVersion: 2010-09-09
Description:  CFN Init Demo - Just create Metadata Template run this template in us-east-2 ohio region


Parameters:
  ImageId:
    Type: String
    Description: Default Imageid for ohio us-east-2 region
    Default: ami-0cd3dfa4e37921605
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Choose the EC2 Key
  InstanceType:
    Type: String
    Description: Default Instance type is t2.micro
    Default: t2.micro
  


Resoureces:
  TestSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: TestSG
      SecurityGroupIngress:
        - IpProtocol: tcp
          ToPort: 22
          FromPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          ToPort: 8080
          FromPort: 8080
          CidrIp: 0.0.0.0/0
  TestEC2:
    Type: AWS::EC2::Instance
    Metadata:
      Comment: Deploy a simple Tomcat application 
      AWS::Cloudformation::Init:
        config:
          package:
          groups:
          users:
          sources:
          files:
          commands:
          services:
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref TestSecurityGroup

