AWSTemplateFormatVersion: 2010-09-09
Description: "To Create EC2 machine and security  group"
Resources:
  DevEC2Instance:
    Type: 'AWS::EC2::Instance'
    Description: "To create test machine"
    Properties:
      ImageId: ami-04ca7d516f2843a7a
      InstanceType: t2.micro
      KeyName: sachin
      SecurityGroups: 
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: my new SSH SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
       