AWSTemplateFormatVersion: 2010-09-09
Description:  Conditions Practice


Parameters:
  MyKeyName:
    Description: Select Key name for the list
    Type: AWS::EC2::KeyPair::KeyName
  EnvironmentName:
    Type: String
    Description: We will use EC2 machine type based on ENV
    Default: dev
    AllowedValues: 
      - dev
      - prod

Mappings:
  MyRegion:
    us-east-1:
      ImageId: ami-0d5eff06f840b45e9
    us-east-2:
      ImageId: ami-077e31c4939f6a2f3
  Myinstance:
    dev:
      Type: t2.small
    prod:
      Type: t2.micro


Resources:
  TestMachine:
    Type: AWS::EC2::Instance
    Description: Creating test machine
    Properties:
      ImageId: !FindInMap
        - MyRegion
        - !Ref AWS::Region
        - ImageId
      InstanceType: !FindInMap
        - Myinstance
        - !Ref EnvironmentName
        - Type
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - !Ref AllowSSH
  AllowSSH:
    Type: AWS::EC2::SecurityGroup
    Description: Creating Security Group
    Properties:
      GroupDescription: My SSH security  group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0        
    