AWSTemplateFormatVersion: 2010-09-09
Description: Condition Example

Parameters:
  EnvKeyName:
    Description: To use existing KeyName value for test machine
    Type: AWS::EC2::KeyPair::KeyName
  ENVType:
    Description: Choose Your environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: must be development or production


Mappings:
  ImageIdentification:
    us-east-1:
      ImageId: ami-0d5eff06f840b45e9
    us-east-2:
      ImageId: ami-077e31c4939f6a2f3
  EC2Type:
    dev:
      InstanceType: t2.small
    prod:
      InstanceType: t2.micro

Conditions:
  CreatePubilcIp: !Equals [ !Ref ENVType, prod ]

Resources:
  TestMachine:
    Type: AWS::EC2::Instance
    Description: we will create testing machine for lab
    Properties:
      ImageId: !FindInMap
        - ImageIdentification
        - !Ref AWS::Region
        - ImageId
      InstanceType: !FindInMap
        - EC2Type
        - !Ref ENVType
        - InstanceType
      KeyName: !Ref EnvKeyName
      
  EIPAddress:
    Type: AWS::EC2::EIP
    Condition: CreatePubilcIp
    Description: We will use this Ip for Prod Env
    Properties:
      InstanceId: !Ref TestMachine

