AWSTemplateFormatVersion: 2010-09-09
Description: Condition Template

Parameters:
  MyKeyName:
    Description: Select Key Name for your Instance 
    Type: AWS::EC2::KeyPair::KeyName
  EnvName:
    Description: Mention Your environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod


Mappings:
  ImageIdentification:
    us-east-1:
      ImageId: ami-0d5eff06f840b45e9
    us-east-2:
      ImageId: ami-077e31c4939f6a2f3
  EC2Type:
    dev:
      InstanceType: t2.small
    prod:
      InstanceType: t2.micro


Conditions: 
  CreateEIPforPROD: !Equals [ !Ref EnvName, prod  ]
  CreateSecurityGroupforDev: !Equals [!Ref EnvName, dev]


Resources:
  TestMachine:
    Type: AWS::EC2::Instance
    Description: EC2 Machine for test lab
    Properties:
      ImageId: !FindInMap
        - ImageIdentification
        - !Ref AWS::Region
        - ImageId
      InstanceType: !FindInMap
        - EC2Type
        - !Ref EnvName
        - InstanceType
      KeyName: !Ref MyKeyName
      SecurityGroups: !If [CreateSecurityGroupforDev, [!Ref AllowSSH], !Ref 'AWS::NoValue'] 
      
      

  TestEIP:
    Type: AWS::EC2::EIP
    Condition: CreateEIPforPROD
    Properties:
      InstanceId: !Ref TestMachine

  AllowSSH:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateSecurityGroupforDev
    Properties:
      GroupDescription: DevSG
      SecurityGroupIngress:
        IpProtocol: tcp
        ToPort: 22
        FromPort: 22
        CidrIp: 0.0.0.0/0





