AWSTemplateFormatVersion: 2010-09-09
Description: Userdata to install tomcat application

Parameters:
  InstanceSize:
    Type: String
    Description: Select Machine as per your Business requirement
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Default:  t2.micro
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the appropriate key for EC2
  AvailabilityZone:
    Type: String
    Description: Choose the AV for EC2
    Default: us-east-1a
    AllowedValues:
      - us-east-1a
      - us-east-1b
      - us-east-1c
  EnvironmentName:
    Type: String
    Description: Select your ENV
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      Label:
        default: "EC2 Instance Configuration"
      Parameters:
        - InstanceSize
        - KeyName
        - AvailabilityZone
      Label:
        default: "Environement configuration"
      Parameters:
        - EnvironmentName
    ParameterLabels:
      EnvironmentName:
        default: "Which environment we are planning to create this instance?"
      KeyName:
        default: "Be aware that once keyname is selected we cannot change it unless instance replaced"


Conditions:
  CreateEIPProd: !Equals [!Ref EnvironmentName, prod]
Resources:
  TestEC2:
    Type: AWS::EC2::Instance
    Description: Creating EC2 for testing purpose
    Properties:
      ImageId: ami-0d5eff06f840b45e9
      InstanceType: !Ref InstanceSize
      KeyName: !Ref KeyName
      AvailabilityZone: !Ref AvailabilityZone
      SecurityGroups:
        - !Ref TestSG
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update
          sudo yum -y erase java-1.7.0-openjdk.x86_64
          sudo yum -y install java-1.8.0-openjdk.x86_64
          sudo yum -y install java-1.8.0-openjdk-devel
          sudo yum -y install tomcat
          service tomcat start
          mkdir /usr/share/tomcat/webapps/ROOT
          touch /usr/share/tomcat/webapps/ROOT/index.html
          echo "Cloud Formation Tomcat Stack" > /usr/share/tomcat/webapps/ROOT/index.html


  TestSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Create your Test security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          ToPort: 22
          FromPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          ToPort: 8080
          FromPort: 8080
          CidrIp: 0.0.0.0/0
  
  ProdEIP:
    Type: AWS::EC2::EIP
    Condition: CreateEIPProd
    Properties:
      InstanceId: !Ref TestEC2



Outputs:
  ApplicationURL:
    Description: Application URL
    Value: !Sub 'http://${TestEC2.PublicDnsName}:8080/index.html'
  
