AWSTemplateFormatVersion: 2010-09-09
Description: Ec2 user data 


Parameters:
  InstanceSize:
    Type: String
    Description: Choose your InstanceType Based on your requirment
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Choose the Key for accessing EC2 VM.
  AvailabilityZone:
    Type: String
    Description: Select the AV, where you want to  deploy your EC2
    Default: us-east-1a
    AllowedValues:
      - us-east-1a
      - us-east-1b
      - us-east-1c
  EnvironmentName:
    Type: String
    Description: Select your Enviroment
    Default: dev
    AllowedValues:
      - dev
      - prod
      - qa


Conditions: 
  CreateEIPProd: !Equals [!Ref EnvironmentName, prod]

Metadata:
  AWS::Cloudformation::Interface:
    ParameterGroups:
      - Label:
          default: "EC2 Instance Configuration"
        Parameters:
          - InstanceSize
          - AvailabilityZone 
          - KeyName
      - Label:
          default: "Environment variable"
        Parameters:
         - EnvironmentName     
    ParametersLables:
      EnvironmentName:
        default: "Which environment we are planning to create this instance?"
      KeyName:
        default: "Be aware that once keyname is selected we cannot change it unless instance replaced"




Resources:
  TESTEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9
      InstanceType:  !Ref InstanceSize
      KeyName: !Ref KeyName
      AvailabilityZone: !Ref AvailabilityZone
      SecurityGroups:
        - !Ref TESTSG
  

  TESTSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG group
      SecurityGroupIngress:
        - IpProtocol: tcp
          ToPort: 22
          FromPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol:  tcp
          ToPort: 8080
          FromPort: 8080
          CidrIp: 0.0.0.0/0
  
  ProdEIP:
    Type: AWS::EC2::EIP
    Condition: CreateEIPProd
    Properties:
      InstanceId: !Ref TESTEC2